# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.5.1"
cmdr = "evaera/cmdr@1.12.0"
promise = "evaera/promise@4.0.0"
knit = "sleitnick/knit@1.7.0"
profileservice = "firebird702/profileservice@1.1.0"
wally = "UpliftGames/wally@0.3.2"
