[package]
name = "joao/projeto-dragon-city"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
cmdr = "evaera/cmdr@1.12.0"
promise = "evaera/promise@4.0.0"
knit = "sleitnick/knit@1.7.0"